MPY: soft reboot
Scanning for BLE Beacon named Central...
Traceback (most recent call last):
  File "<stdin>", line 198, in <module>
  File "asyncio/core.py", line 1, in run
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 196, in main
  File "asyncio/funcs.py", line 1, in gather
  File "asyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 146, in run_central_mode
  File "<stdin>", line 136, in ble_scan
  File "aioble/central.py", line 202, in name
UnicodeError: